"""Made every column nullable = False

Revision ID: 20cd8ca0cb1d
Revises: f852b851d9f8
Create Date: 2026-09-19 02:47:19.385225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cd8ca0cb1d'
down_revision: Union[str, Sequence[str], None] = 'f852b851d9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
