"""Made every column nullable = False

Revision ID: 2a5e0b691080
Revises: 20cd8ca0cb1d
Create Date: 2026-09-19 02:55:07.133092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5e0b691080'
down_revision: Union[str, Sequence[str], None] = '20cd8ca0cb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('courses', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('courses', 'unit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'lecturer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('students', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('students', 'password_hashed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('password_hashed', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('students', 'password')
    op.alter_column('courses', 'lecturer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('courses', 'unit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
