"""Initial migration

Revision ID: a15477c29ae2
Revises: 553b9ae7d8fa
Create Date: 2026-09-17 23:10:19.905456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15477c29ae2'
down_revision: Union[str, Sequence[str], None] = '553b9ae7d8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('eye_colour', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'eye_colour')
    # ### end Alembic commands ###
