"""Added password column

Revision ID: ba72739b94f9
Revises: a15477c29ae2
Create Date: 2026-09-18 01:17:55.242782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba72739b94f9'
down_revision: Union[str, Sequence[str], None] = 'a15477c29ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('password_hashed', sa.String(), nullable=False))
    op.drop_column('students', 'eye_colour')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('eye_colour', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'password_hashed')
    # ### end Alembic commands ###
